#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#                       This file was automatically generated from modular_openpangu_dense.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_openpangu_dense.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨

# coding=utf-8
# Copyright (c) 2025 Huawei Technologies Co., Ltd. All rights reserved.
# Copyright 2022 EleutherAI and the HuggingFace Inc. team. All rights reserved.
#
# This code is based on EleutherAI's GPT-NeoX library and the GPT-NeoX
# and OPT implementations in this library. It has been modified from its
# original forms to accommodate minor architectural differences compared
# to GPT-NeoX and OPT used by the Meta AI team that trained the model.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Callable, Optional, Union

import torch
from torch import nn

import torch_npu
from torch_npu.contrib import transfer_to_npu
# if "910" in torch.npu.get_device_name():
#     NPU_ATTN_INFR = True
#     print("[INFO] torch_npu detected. Using NPU fused infer attention.")
# else:
#     NPU_ATTN_INFR = False

NPU_ATTN_INFR = True  # ! set always True here to prevent subprocess errors

from transformers.activations import ACT2FN
from transformers.cache_utils import Cache, DynamicCache
from transformers.generation import GenerationMixin
from transformers.masking_utils import create_causal_mask
from transformers.modeling_flash_attention_utils import FlashAttentionKwargs
from transformers.modeling_layers import GradientCheckpointingLayer
from transformers.modeling_outputs import (
    BaseModelOutputWithPast,
    CausalLMOutputWithPast,
    SequenceClassifierOutputWithPast,
)
from transformers.modeling_rope_utils import ROPE_INIT_FUNCTIONS, dynamic_rope_update
from transformers.modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from transformers.processing_utils import Unpack
from transformers.utils import LossKwargs, auto_docstring, can_return_tuple, logging
from transformers.configuration_utils import PretrainedConfig
from .configuration_openpangu_dense import PanguEmbeddedConfig


logger = logging.get_logger(__name__)


class PanguEmbeddedConfig(PretrainedConfig):

    model_type = "PanguEmbedded"
    _auto_class = "AutoConfig"

    def __init__(
        self,
        vocab_size=153376,
        hidden_size=4096,
        intermediate_size=12800,
        num_hidden_layers=34,
        num_attention_heads=32,
        num_key_value_heads=8,
        hidden_act="silu",
        max_position_embeddings=32768,
        initializer_range=0.02,
        rms_norm_eps=1e-5,
        use_cache=True,
        pad_token_id=0,
        bos_token_id=1,
        eos_token_id=45892,
        tie_word_embeddings=False,
        rope_theta=16000000.0,
        bias=True,
        **kwargs,
    ):
        self.vocab_size = vocab_size
        self.max_position_embeddings = max_position_embeddings
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.num_key_value_heads = num_key_value_heads
        self.hidden_act = hidden_act
        self.initializer_range = initializer_range
        self.rms_norm_eps = rms_norm_eps
        self.use_cache = use_cache
        self.rope_theta = rope_theta
        self.bias = bias
        super().__init__(
            pad_token_id=pad_token_id,
            bos_token_id=bos_token_id,
            eos_token_id=eos_token_id,
            tie_word_embeddings=tie_word_embeddings,
            **kwargs,
        )


class PanguEmbeddedRMSNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-6):
        """
        PanguEmbeddedRMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def forward(self, hidden_states):
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


class PanguEmbeddedRotaryEmbedding(nn.Module):
    def __init__(self, config: PanguEmbeddedConfig, device=None):
        super().__init__()
        # BC: "rope_type" was originally "type"
        if hasattr(config, "rope_scaling") and config.rope_scaling is not None:
            self.rope_type = config.rope_scaling.get("rope_type", config.rope_scaling.get("type"))
        else:
            self.rope_type = "default"
        self.max_seq_len_cached = config.max_position_embeddings
        self.original_max_seq_len = config.max_position_embeddings

        self.config = config
        self.rope_init_fn = ROPE_INIT_FUNCTIONS[self.rope_type]

        inv_freq, self.attention_scaling = self.rope_init_fn(self.config, device)
        self.register_buffer("inv_freq", inv_freq, persistent=False)
        self.original_inv_freq = self.inv_freq

    @torch.no_grad()
    @dynamic_rope_update  # power user: used with advanced RoPE types (e.g. dynamic rope)
    def forward(self, x, position_ids):
        inv_freq_expanded = self.inv_freq[None, :, None].float().expand(position_ids.shape[0], -1, 1).to(x.device)
        position_ids_expanded = position_ids[:, None, :].float()

        device_type = x.device.type if isinstance(x.device.type, str) and x.device.type != "mps" else "cpu"
        with torch.autocast(device_type=device_type, enabled=False):  # Force float32
            freqs = (inv_freq_expanded.float() @ position_ids_expanded.float()).transpose(1, 2)
            emb = torch.cat((freqs, freqs), dim=-1)
            cos = emb.cos() * self.attention_scaling
            sin = emb.sin() * self.attention_scaling

        return cos.to(dtype=x.dtype), sin.to(dtype=x.dtype)


def rotate_half(x):
    """Rotates half the hidden dims of the input."""
    x1 = x[..., : x.shape[-1] // 2]
    x2 = x[..., x.shape[-1] // 2 :]
    return torch.cat((-x2, x1), dim=-1)


def apply_rotary_pos_emb(q, k, cos, sin, position_ids=None, unsqueeze_dim=1):
    """Applies Rotary Position Embedding to the query and key tensors.

    Args:
        q (`torch.Tensor`): The query tensor.
        k (`torch.Tensor`): The key tensor.
        cos (`torch.Tensor`): The cosine part of the rotary embedding.
        sin (`torch.Tensor`): The sine part of the rotary embedding.
        position_ids (`torch.Tensor`, *optional*):
            Deprecated and unused.
        unsqueeze_dim (`int`, *optional*, defaults to 1):
            The 'unsqueeze_dim' argument specifies the dimension along which to unsqueeze cos[position_ids] and
            sin[position_ids] so that they can be properly broadcasted to the dimensions of q and k. For example, note
            that cos[position_ids] and sin[position_ids] have the shape [batch_size, seq_len, head_dim]. Then, if q and
            k have the shape [batch_size, heads, seq_len, head_dim], then setting unsqueeze_dim=1 makes
            cos[position_ids] and sin[position_ids] broadcastable to the shapes of q and k. Similarly, if q and k have
            the shape [batch_size, seq_len, heads, head_dim], then set unsqueeze_dim=2.
    Returns:
        `tuple(torch.Tensor)` comprising of the query and key tensors rotated using the Rotary Position Embedding.
    """
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)
    q_embed = (q * cos) + (rotate_half(q) * sin)
    k_embed = (k * cos) + (rotate_half(k) * sin)
    return q_embed, k_embed


class PanguEmbeddedMLP(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.up_proj = nn.Linear(self.hidden_size, self.intermediate_size, bias=False)
        self.down_proj = nn.Linear(self.intermediate_size, self.hidden_size, bias=False)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
        return down_proj


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: Optional[torch.Tensor],
    scaling: float,
    dropout: float = 0.0,
    **kwargs,
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        causal_mask = attention_mask[:, :, :, : key_states.shape[-2]]
        attn_weights = attn_weights + causal_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


class PanguEmbeddedAttention(nn.Module):
    """Multi-headed attention from 'Attention Is All You Need' paper"""

    def __init__(self, config: PanguEmbeddedConfig, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.head_dim = getattr(config, "head_dim", config.hidden_size // config.num_attention_heads)
        self.num_heads = config.num_attention_heads
        self.num_key_value_heads = config.num_key_value_heads
        self.num_key_value_groups = config.num_attention_heads // config.num_key_value_heads
        self.scaling = self.head_dim**-0.5
        self.attention_dropout = config.attention_dropout
        self.is_causal = True

        self.q_proj = nn.Linear(config.hidden_size, config.num_attention_heads * self.head_dim, bias=config.bias)
        self.k_proj = nn.Linear(config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.bias)
        self.v_proj = nn.Linear(config.hidden_size, config.num_key_value_heads * self.head_dim, bias=config.bias)
        self.o_proj = nn.Linear(config.num_attention_heads * self.head_dim, config.hidden_size, bias=config.bias)

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor],
        attention_mask: Optional[torch.Tensor],
        past_key_value: Optional[Cache] = None,
        cache_position: Optional[torch.LongTensor] = None,
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.Tensor, Optional[torch.Tensor], Optional[tuple[torch.Tensor]]]:
        input_shape = hidden_states.shape[:-1]
        hidden_shape = (*input_shape, -1, self.head_dim)

        query_states = self.q_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        key_states = self.k_proj(hidden_states).view(hidden_shape).transpose(1, 2)
        value_states = self.v_proj(hidden_states).view(hidden_shape).transpose(1, 2)

        cos, sin = position_embeddings
        query_states, key_states = apply_rotary_pos_emb(query_states, key_states, cos, sin)

        if past_key_value is not None:
            # sin and cos are specific to RoPE models; cache_position needed for the static cache
            cache_kwargs = {"sin": sin, "cos": cos, "cache_position": cache_position}
            key_states, value_states = past_key_value.update(key_states, value_states, self.layer_idx, cache_kwargs)

        attention_interface: Callable = eager_attention_forward
        if self.config._attn_implementation != "eager":
            attention_interface = ALL_ATTENTION_FUNCTIONS[self.config._attn_implementation]
        
        if not self.training and NPU_ATTN_INFR:
            q_len = input_shape[1]
            if attention_mask is not None:
                attention_mask = ~attention_mask.bool()
            elif q_len > 1:
                attention_mask = torch.triu(torch.ones([q_len, q_len]), diagonal=1).bool().unsqueeze(0).unsqueeze(0).to(query_states.device)

            attn_output, _ = torch_npu.npu_fused_infer_attention_score(
                query_states, key_states, value_states,
                num_heads=self.num_heads, num_key_value_heads=self.num_key_value_heads,
                input_layout="BNSD", atten_mask=attention_mask, scale=self.scaling)
            attn_output = attn_output.transpose(1, 2)
            attn_weights = None
        else:
            attn_output, attn_weights = attention_interface(
                self,
                query_states,
                key_states,
                value_states,
                attention_mask,
                dropout=0.0 if not self.training else self.attention_dropout,
                scaling=self.scaling,
                **kwargs,
            )

        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        attn_output = self.o_proj(attn_output)
        return attn_output, attn_weights


class PanguEmbeddedDecoderLayer(GradientCheckpointingLayer):
    def __init__(self, config: PanguEmbeddedConfig, layer_idx: int):
        super().__init__()
        self.hidden_size = config.hidden_size
        self.self_attn = PanguEmbeddedAttention(config=config, layer_idx=layer_idx)
        self.mlp = PanguEmbeddedMLP(config)
        self.input_layernorm = PanguEmbeddedRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.post_attention_layernorm = PanguEmbeddedRMSNorm(config.hidden_size, eps=config.rms_norm_eps)

    def forward(
        self,
        hidden_states: torch.Tensor,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_value: Optional[Cache] = None,
        output_attentions: Optional[bool] = False,
        use_cache: Optional[bool] = False,
        cache_position: Optional[torch.LongTensor] = None,
        position_embeddings: Optional[tuple[torch.Tensor, torch.Tensor]] = None,  # necessary, but kept here for BC
        **kwargs: Unpack[FlashAttentionKwargs],
    ) -> tuple[torch.FloatTensor, Optional[tuple[torch.FloatTensor, torch.FloatTensor]]]:
        residual = hidden_states
        hidden_states = self.input_layernorm(hidden_states)

        # Self Attention
        hidden_states, self_attn_weights = self.self_attn(
            hidden_states=hidden_states,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_value=past_key_value,
            output_attentions=output_attentions,
            use_cache=use_cache,
            cache_position=cache_position,
            position_embeddings=position_embeddings,
            **kwargs,
        )
        hidden_states = residual + hidden_states

        # Fully Connected
        residual = hidden_states
        hidden_states = self.post_attention_layernorm(hidden_states)
        hidden_states = self.mlp(hidden_states)
        hidden_states = residual + hidden_states

        outputs = (hidden_states,)
        if output_attentions:
            outputs += (self_attn_weights,)

        return outputs


@auto_docstring
class PanguEmbeddedPreTrainedModel(PreTrainedModel):
    config_class = PanguEmbeddedConfig
    base_model_prefix = "model"
    supports_gradient_checkpointing = True
    _no_split_modules = ["PanguEmbeddedDecoderLayer"]
    _skip_keys_device_placement = ["past_key_values"]
    _supports_flash_attn_3 = True
    _supports_flash_attn_2 = True
    _supports_sdpa = True
    _supports_flex_attn = True
    _supports_cache_class = True
    _supports_quantized_cache = True
    _supports_static_cache = True
    _supports_attention_backend = True

    def _init_weights(self, module):
        std = self.config.initializer_range
        if isinstance(module, nn.Linear):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.bias is not None:
                module.bias.data.zero_()
        elif isinstance(module, nn.Embedding):
            module.weight.data.normal_(mean=0.0, std=std)
            if module.padding_idx is not None:
                module.weight.data[module.padding_idx].zero_()
        elif isinstance(module, PanguEmbeddedRMSNorm):
            module.weight.data.fill_(1.0)


@auto_docstring
class PanguEmbeddedModel(PanguEmbeddedPreTrainedModel):
    def __init__(self, config: PanguEmbeddedConfig):
        super().__init__(config)
        self.padding_idx = config.pad_token_id
        self.vocab_size = config.vocab_size

        self.embed_tokens = nn.Embedding(config.vocab_size, config.hidden_size, self.padding_idx)
        self.layers = nn.ModuleList(
            [PanguEmbeddedDecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.norm = PanguEmbeddedRMSNorm(config.hidden_size, eps=config.rms_norm_eps)
        self.rotary_emb = PanguEmbeddedRotaryEmbedding(config=config)
        self.gradient_checkpointing = False

        # Initialize weights and apply final processing
        self.post_init()

    def get_input_embeddings(self):
        return self.embed_tokens

    def set_input_embeddings(self, value):
        self.embed_tokens = value

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        # ! ------ steering ------
        steering_flag: Optional[torch.BoolTensor] = None,
        steering_vector: Optional[torch.FloatTensor] = None,
        steering_layer: Optional[int] = None,
        steering_coef: Optional[float] = 0.0,
        # ! ------ steering ------
        **flash_attn_kwargs: Unpack[FlashAttentionKwargs],
    ) -> BaseModelOutputWithPast:
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        use_cache = use_cache if use_cache is not None else self.config.use_cache

        if (input_ids is None) ^ (inputs_embeds is not None):
            raise ValueError("You must specify exactly one of input_ids or inputs_embeds")

        if self.gradient_checkpointing and self.training and use_cache:
            logger.warning_once(
                "`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`."
            )
            use_cache = False

        # TODO (joao): remove this exception in v4.56 -- it exists for users that try to pass a legacy cache
        if not isinstance(past_key_values, (type(None), Cache)):
            raise ValueError("The `past_key_values` should be either a `Cache` object or `None`.")

        if inputs_embeds is None:
            inputs_embeds = self.embed_tokens(input_ids)

        if use_cache and past_key_values is None:
            past_key_values = DynamicCache()

        if cache_position is None:
            past_seen_tokens = past_key_values.get_seq_length() if past_key_values is not None else 0
            cache_position = torch.arange(
                past_seen_tokens, past_seen_tokens + inputs_embeds.shape[1], device=inputs_embeds.device
            )

        if position_ids is None:
            position_ids = cache_position.unsqueeze(0)

        causal_mask = create_causal_mask(
            config=self.config,
            input_embeds=inputs_embeds,
            attention_mask=attention_mask,
            cache_position=cache_position,
            past_key_values=past_key_values,
            position_ids=position_ids,
        )

        hidden_states = inputs_embeds

        # create position embeddings to be shared across the decoder layers
        position_embeddings = self.rotary_emb(hidden_states, position_ids)

        # decoder layers
        all_hidden_states = () if output_hidden_states else None
        all_self_attns = () if output_attentions else None

        for l, decoder_layer in enumerate(self.layers[: self.config.num_hidden_layers]):
            # ! ------ steering ------
            if steering_flag is not None and steering_layer == l:
                steering_vector = steering_vector.to(hidden_states.dtype).to(hidden_states.device)
                steering_flag = steering_flag.to(hidden_states.device)
                # support tensor (per-sample) or scalar coefficient
                if isinstance(steering_coef, torch.Tensor):
                    coef = steering_coef.to(hidden_states.dtype).to(hidden_states.device)[steering_flag].unsqueeze(1)
                else:
                    coef = torch.as_tensor(steering_coef, dtype=hidden_states.dtype, device=hidden_states.device)
                hidden_states[steering_flag, -1] += coef * steering_vector
            # ! ------ steering ------
            
            if output_hidden_states:
                all_hidden_states += (hidden_states,)

            layer_outputs = decoder_layer(
                hidden_states,
                attention_mask=causal_mask,
                position_ids=position_ids,
                past_key_value=past_key_values,
                output_attentions=output_attentions,
                use_cache=use_cache,
                cache_position=cache_position,
                position_embeddings=position_embeddings,
                **flash_attn_kwargs,
            )

            hidden_states = layer_outputs[0]

            if output_attentions:
                all_self_attns += (layer_outputs[1],)

        hidden_states = self.norm(hidden_states)

        # ! ------ steering ------
        if steering_flag is not None and steering_layer == len(self.layers):
            steering_vector = steering_vector.to(hidden_states.dtype).to(hidden_states.device)
            steering_flag = steering_flag.to(hidden_states.device)
            if isinstance(steering_coef, torch.Tensor):
                coef = steering_coef.to(hidden_states.dtype).to(hidden_states.device)[steering_flag].unsqueeze(1)
            else:
                coef = torch.as_tensor(steering_coef, dtype=hidden_states.dtype, device=hidden_states.device)
            hidden_states[steering_flag, -1] += coef * steering_vector
        # ! ------ steering ------

        # add hidden states from the last decoder layer
        if output_hidden_states:
            all_hidden_states += (hidden_states,)

        return BaseModelOutputWithPast(
            last_hidden_state=hidden_states,
            past_key_values=past_key_values if use_cache else None,
            hidden_states=all_hidden_states,
            attentions=all_self_attns,
        )


class KwargsForCausalLM(FlashAttentionKwargs, LossKwargs): ...


@auto_docstring
class PanguEmbeddedForCausalLM(PanguEmbeddedPreTrainedModel, GenerationMixin):
    _tied_weights_keys = ["lm_head.weight"]
    _tp_plan = {"lm_head": "colwise_rep"}
    _pp_plan = {"lm_head": (["hidden_states"], ["logits"])}

    def __init__(self, config):
        super().__init__(config)
        self.model = PanguEmbeddedModel(config)
        self.vocab_size = config.vocab_size
        self.lm_head = nn.Linear(config.hidden_size, config.vocab_size, bias=False)

        # ! ------ steering ------
        self.new_round=False
        self.cur_steps = 0

        self.steering_flag = False
        self.steering_vector = None
        self.steering_layer = None
        self.steering_coef = 0.0
        self.steering_think_flag=None
        self._prev_step_mean = None  # for two-step variance

        self.steering_split_ids = None
        self.steering_think_start_id=None
        self.steering_think_end_id=None

        # --- dynamic steering internals (no extra CLI flags required)
        self._dyn_enabled = True
        self._coefs = None              # per-sample dynamic coefficients
        self._step_prob_sum = None      # sum of max-prob within a segment
        self._step_tok_count = None     # token count within a segment
        self._last_maxprob = None       # max-prob of the last token from previous step

        # --- dynamic steering parameters (can be configured outside)
        self.q25c = None
        self.q75c = None
        self.low_val_1 = None
        self.high_val_1 = None
        self.q25v = None
        self.q75v = None
        self.low_val_2 = None
        self.high_val_2 = None
        # ! ------ steering ------

        # Initialize weights and apply final processing
        self.post_init()
    
    # ! ------ steering ------
    def set_steering_flag(self, steering_flag, steering_layer=None, steer_vec=None, steer_coef=0.0, tokenizer=None, low_val_2=None, high_val_2=None):
        self.steering_flag = steering_flag
        self.steering_vector = steer_vec
        self.steering_layer = steering_layer
        self.steering_coef = steer_coef
        self.steering_think_flag=None
        self.steering_split_ids = None
        self.steering_think_start_id=None
        self.steering_think_end_id=None
        if steering_flag:
            assert steering_layer is not None, "Steering layer must be provided for steering"
            assert steer_vec is not None, "Steering vector must be provided for steering"
            assert tokenizer is not None, "Tokenizer must be provided for steering"
            vocab = tokenizer.get_vocab()
            self.steering_split_ids = torch.LongTensor([vocab[token] for token in vocab.keys() if "\n\n" in token]).to(self.device)  # ! adapt to pangu
            self.steering_think_start_id = tokenizer.encode("[unused16]", add_special_tokens=False)[0]
            self.steering_think_end_id =  tokenizer.encode("[unused17]", add_special_tokens=False)[0]
        # reset dynamic state
        self._coefs = None
        self._step_prob_sum = None
        self._step_tok_count = None
        self._last_maxprob = None
        self.low_val_2 = low_val_2
        self.high_val_2 = high_val_2

    
    def start_new_round(self):
        self.new_round=True
        self.cur_steps = 0
        self.steering_think_flag=None
    # ! ------ steering ------

    def get_input_embeddings(self):
        return self.model.embed_tokens

    def set_input_embeddings(self, value):
        self.model.embed_tokens = value

    def get_output_embeddings(self):
        return self.lm_head

    def set_output_embeddings(self, new_embeddings):
        self.lm_head = new_embeddings

    def set_decoder(self, decoder):
        self.model = decoder

    def get_decoder(self):
        return self.model

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        input_ids: Optional[torch.LongTensor] = None,
        attention_mask: Optional[torch.Tensor] = None,
        position_ids: Optional[torch.LongTensor] = None,
        past_key_values: Optional[Cache] = None,
        inputs_embeds: Optional[torch.FloatTensor] = None,
        labels: Optional[torch.LongTensor] = None,
        use_cache: Optional[bool] = None,
        output_attentions: Optional[bool] = None,
        output_hidden_states: Optional[bool] = None,
        cache_position: Optional[torch.LongTensor] = None,
        logits_to_keep: Union[int, torch.Tensor] = 0,
        **kwargs: Unpack[KwargsForCausalLM],
    ) -> CausalLMOutputWithPast:
 
        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )


        # ! ------ steering ------
        # global steering flag
        if self.steering_flag:
            if self.new_round:
                self.new_round=False
                # self.steering_think_flag=torch.zeros(input_ids.shape[0], device=input_ids.device).to(torch.bool)
                self.steering_think_flag = (input_ids==self.steering_think_start_id).sum(1).to(torch.bool)
            else:
                assert input_ids.shape[1]==1, "use cache"
            last_tokens = input_ids[:,-1]
            self.steering_think_flag = torch.logical_or(self.steering_think_flag, last_tokens==self.steering_think_start_id)
            self.steering_think_flag = torch.logical_and(self.steering_think_flag, last_tokens!=self.steering_think_end_id)
            # local steering flag
            split_flag = torch.isin(last_tokens, self.steering_split_ids.to(input_ids.device))
            steering_flag = torch.logical_and(split_flag, self.steering_think_flag)
            if not torch.any(steering_flag):
                steering_flag = None
        else:
            steering_flag = None

        self.cur_steps += 1



        # --- dynamic coefficient tracking & update (confidence-based) ---
        if self.steering_flag and getattr(self, "_dyn_enabled", True):
            bsz = input_ids.shape[0]
            device = input_ids.device
            # init buffers
            if self._coefs is None or self._coefs.shape[0] != bsz:
                self._coefs = torch.full((bsz,), float(self.steering_coef), dtype=torch.float32, device=device)
            if self._step_prob_sum is None or self._step_prob_sum.shape[0] != bsz:
                self._step_prob_sum = torch.zeros(bsz, dtype=torch.float32, device=device)
                self._step_tok_count = torch.zeros(bsz, dtype=torch.long, device=device)

            # accumulate prev-step max-prob for non-split tokens
            if self._last_maxprob is not None:
                not_split_prev = ~split_flag
                self._step_prob_sum[not_split_prev] += self._last_maxprob[not_split_prev]
                self._step_tok_count[not_split_prev] += 1

            # on split boundary, update coef using mean of max-prob in the segment
            ready_mask = torch.logical_and(split_flag, self._step_tok_count > 0)
            if ready_mask.any():
                mean_max = self._step_prob_sum[ready_mask] / self._step_tok_count[ready_mask].float()
                # piecewise with smooth middle: <=0.70 -> -3.0; >=0.90 -> -0.1; else sigmoid around tau=0.8
                
                # === Dynamic Control ===
                bsz = input_ids.shape[0]
                if (self._prev_step_mean is None) or (self._prev_step_mean.shape[0] != bsz):
                    self._prev_step_mean = torch.full(
                        (bsz,), float('nan'),
                        dtype=torch.float32, device=input_ids.device
                    )

                prev_vals = self._prev_step_mean[ready_mask]
                has_prev = torch.isfinite(prev_vals)
                var_conf = torch.zeros_like(mean_max, dtype=torch.float32, device=mean_max.device)
                var_conf[has_prev] = ((mean_max[has_prev] - prev_vals[has_prev]) ** 2) / 4.0

                # 1D F(c)
                import math as _m

                def _solve_k_for_tau(q25, q75, low_val, high_val, tau, iters=80):
                    m = 0.5 * (q25 + q75)
                    s = max(1e-9, 0.5 * (q75 - q25))
                    denom = max(high_val - low_val, 1e-12)
                    R_target = (2.0 * (tau - 0.5 * (low_val + high_val))) / denom
                    def ratio(k):
                        num = _m.tanh(k * max(0.0, 1.0 - m))
                        ks = k * s
                        den = _m.tanh(ks) if ks > 1e-12 else ks
                        return num / den if den > 0 else float('inf')
                    lo, hi = 1e-6, 1.0
                    while ratio(hi) > R_target and hi < 1e6:
                        hi *= 2.0
                    for _ in range(iters):
                        mid = 0.5 * (lo + hi)
                        if ratio(mid) > R_target:
                            lo = mid
                        else:
                            hi = mid
                    return 0.5 * (lo + hi)

                def build_F(q25, q75, low_val=-3.0, high_val=0.0, tau=0.1):
                    m = 0.5 * (q25 + q75)
                    s = max(1e-9, 0.5 * (q75 - q25))
                    k = _solve_k_for_tau(q25, q75, low_val, high_val, tau)
                    t = _m.tanh(k * s)
                    a = 0.5 * (low_val + high_val)
                    b = (high_val - low_val) / (2.0 * max(t, 1e-12))
                    def F1(c):
                        if not isinstance(c, torch.Tensor):
                            c = torch.as_tensor(c, dtype=mean_max.dtype, device=mean_max.device)
                        c = torch.nan_to_num(c, nan=0.5, posinf=1.0, neginf=0.0).clamp(0.0, 1.0)
                        a_t = torch.as_tensor(a, device=c.device, dtype=c.dtype)
                        b_t = torch.as_tensor(b, device=c.device, dtype=c.dtype)
                        k_t = torch.as_tensor(k, device=c.device, dtype=c.dtype)
                        m_t = torch.as_tensor(m, device=c.device, dtype=c.dtype)
                        return a_t + b_t * torch.tanh(k_t * (c - m_t))
                    return F1

                q25c = self.q25c if self.q25c is not None else 0.75   # v0:0.75; v1:0.74; v2:0.74
                q75c = self.q75c if self.q75c is not None else 0.92   # v0:0.93; v1:0.92; v2:0.92
                low_val_1 = self.low_val_1 if self.low_val_1 is not None else -0.69  # F(q25c), v0:-1.14; v1:-0.99; v2:-1.17
                high_val_1 = self.high_val_1 if self.high_val_1 is not None else 0.01   # F(1), 0.01

                q25v = self.q25v if self.q25v is not None else 0.000274  # v0:0.000289; v1:0.000263; v2:0.000270
                q75v = self.q75v if self.q75v is not None else 0.005423  # v0:0.005617, v1:0.006008; v2:0.006074
                low_val_2 = self.low_val_2 if self.low_val_2 is not None else -3.30  # f(q25c, q75v)  v0:-5.54; v1:-3.97; v2:-4.0
                high_val_2 = self.high_val_2 if self.high_val_2 is not None else 0.1   # f(1, q25v), 0.1

                q25c, q75c = (min(q25c, q75c), max(q25c, q75c))
                q25v, q75v = (min(q25v, q75v), max(q25v, q75v))

                F1 = build_F(q25c, q75c, low_val=low_val_1, tau=high_val_1)  # baseline F(c)

                # 4) Construct 2D F(c,v)
                IQRc = max(1e-12, (q75c - q25c))
                IQRv = max(1e-12, (q75v - q25v))

                def _sigmoid(x: torch.Tensor) -> torch.Tensor:
                    return torch.sigmoid(x.clamp(-60.0, 60.0))

                # gating
                def g_low_c_t(c):   return _sigmoid((q25c - c) / IQRc * 12.0)
                def g_high_c_t(c):  return _sigmoid((c - q75c) / IQRc * 12.0)
                def g_high_v_t(v):  return _sigmoid((v - q75v) / IQRv * 12.0)
                def g_low_v_t(v):   return _sigmoid((q25v - v) / IQRv * 12.0)

                def _sigm_scalar(x: float) -> float:
                    x = max(min(x, 60.0), -60.0)
                    import math as __m
                    return 1.0 / (1.0 + __m.exp(-x))

                gp = _sigm_scalar((q25c - q25c) / IQRc * 12.0) * _sigm_scalar((q75v - q75v) / IQRv * 12.0)  # ~= 0.25
                gm = _sigm_scalar((1.0  - q75c) / IQRc * 12.0) * _sigm_scalar((q25v - q25v) / IQRv * 12.0)  # ~= 0.5
                eps = 1e-6

                F_q25 = float(F1(torch.tensor(q25c, dtype=mean_max.dtype, device=mean_max.device)))
                F_1   = float(F1(torch.tensor(1.0,   dtype=mean_max.dtype, device=mean_max.device)))

                w_low  = (g_low_c_t(mean_max)  * g_high_v_t(var_conf)) / max(gp, eps)
                w_high = (g_high_c_t(mean_max) * g_low_v_t(var_conf))  / max(gm, eps)
                w_low  = torch.clamp(w_low,  max=1.0)
                w_high = torch.clamp(w_high, max=1.0)

                # compute the updated coefficients
                base = F1(mean_max)
                delta_low  = torch.as_tensor(low_val_2  - F_q25, dtype=mean_max.dtype, device=mean_max.device)
                delta_high = torch.as_tensor(high_val_2 - F_1,   dtype=mean_max.dtype, device=mean_max.device)
                updated = base + delta_low * w_low + delta_high * w_high

                # keep safe
                updated = torch.clamp(updated, min=float(min(low_val_2, low_val_1)), max=float(max(high_val_1, high_val_2)))


                self._coefs[ready_mask] = updated

                # reset accumulators for those samples
                self._step_prob_sum[ready_mask] = 0.0
                self._step_tok_count[ready_mask] = 0

                # update mean confidence
                self._prev_step_mean[ready_mask] = mean_max.detach()


            current_coef = self._coefs
        else:
            current_coef = torch.as_tensor(float(self.steering_coef), dtype=torch.float32, device=input_ids.device)
        # ! ------ steering ------


        # decoder outputs consists of (dec_features, layer_state, dec_hidden, dec_attn)
        outputs: BaseModelOutputWithPast = self.model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            position_ids=position_ids,
            past_key_values=past_key_values,
            inputs_embeds=inputs_embeds,
            use_cache=use_cache,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            cache_position=cache_position,
            **kwargs,
            # ! ------ steering ------
            steering_flag=steering_flag,
            steering_vector=self.steering_vector,
            steering_layer=self.steering_layer,
            steering_coef=current_coef,
            # ! ------ steering ------
        )

        hidden_states = outputs.last_hidden_state
        # Only compute necessary logits, and do not upcast them to float if we are not computing the loss
        slice_indices = slice(-logits_to_keep, None) if isinstance(logits_to_keep, int) else logits_to_keep
        logits = self.lm_head(hidden_states[:, slice_indices, :])

        # ! ------ steering ------
        # cache last-step max probability for dynamic update on the next step
        if self.steering_flag and getattr(self, "_dyn_enabled", True):
            with torch.no_grad():
                probs = torch.softmax(logits[:, -1, :], dim=-1)
                self._last_maxprob = probs.max(dim=-1).values
        # ! ------ steering ------

        loss = None
        if labels is not None:
            loss = self.loss_function(logits=logits, labels=labels, vocab_size=self.config.vocab_size, **kwargs)

        return CausalLMOutputWithPast(
            loss=loss,
            logits=logits,
            past_key_values=outputs.past_key_values,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )


__all__ = [
    "PanguEmbeddedForCausalLM",
    "PanguEmbeddedModel",
    "PanguEmbeddedPreTrainedModel",
]